name: divisas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bloc_test: null
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.0
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  hive: null
  hive_flutter: null
  intl: ^0.17.0
  path_provider: ^2.0.11
  shimmer: ^2.0.0
  connectivity_plus: ^3.0.2

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/mock/
